name: Basic Workflow
on:
  push:
    branches: feature/basic-workflow
jobs:
  do-things:
    name: Do Things
    runs-on: ubuntu-latest
    steps:
      - name: The Thing I've Done
feature/basic-workflow
        run: echo "I've done a thing!"
      - name: An Error I made
        run: |
          echo "I've made an error!"
          exit 1

        run: echo "I've done a thing!!!"
 main
